### ISSUE TITLE
"Check time" does not include time from current session

### ISSUE THREAD

**Issue by SUPERCILEX** [FRCTools/Attendance-Client#21]
Include a bit of text that says something like "Once you have signed out, you will have x hours."

**Comment by evanmhm** [comment]
This is how we want it, check time is only for the hours that have been actually logged.

**Comment by SUPERCILEX** [comment]
After some internal discussion, we've come to the conclusion that the user should see their updated hours, but with a message explaining that they will only get the hours once they've signed out.
