### ISSUE TITLE
Remove leaderboard and add hours progress bar

### ISSUE THREAD

**Issue by will-hou** [FRCTools/Attendance-Client#50]
Remove the hours leaderboard and replace with a progress bar to show off all the hard work and time contributed to the team by every SERT member!

**Comment by will-hou** [comment]
Palmer also suggested modifying the leader board so that it only shows who is currently logged in but not any of their hours, which sounds like a really good idea to me

**Comment by andrewda** [comment]
Good idea! Here's a potential mock-up I just whipped up:

![Untitled](https://user-images.githubusercontent.com/10191084/64833045-4bc9c780-d591-11e9-87b9-a4a07f84fc4e.png)

**Comment by will-hou** [comment]
Something like that would look great to me! 

I've tried to get started but have run into a little bit of trouble with getting MaterialUI Linear Progress bars to work. Will look more into it during the weekend

**Comment by andrewda** [comment]
I'm guessing the current version of MUI is very outdated in this repo. If you haven't already, try updating to 4.0+

**Comment by andrewda** [comment]
Oh jeez, yeah this repo is at 0.18.1, latest version is 4.4.1. Updating will likely require some significant changes in other portions of the app as well.

**Comment by will-hou** [comment]
I've updated all the packages and made enough changes for the front-end elements of the website to show up on the remove-leaderboard branch.

I followed the steps on [the migration guide](https://react-redux-firebase.com/docs/v2-migration-guide.html)  but I'm still unable to get data from Firebase into the application. I'll try to look into it more but I don't have any experience with Firebase so it might take me a while to find out what the issue is. 

~~Also the theme is not working yet so the application is a nice blue color for now haha.~~

Edit: I think I found the issue with the theming:  I didn't migrate everything to material-ui core and there are errors. Will fix asap

**Comment by andrewda** [comment]
@will-hou if you run the `master` version, can you see the Firebase data? Just ruling out the possibility that the credentials are screwed up.

**Comment by will-hou** [comment]
Everything works fine when I run the master version. Good idea to check!

**Comment by will-hou** [comment]
Nvm, we decided that updating all the dependencies to the latest version is probably unnecessary. Issue will be closed in #51 :)

**Comment by will-hou** [comment]
Leaderboard has been removed! See **[`revision`](https://github.com/SouthEugeneRoboticsTeam/attendance-client/tree/revision)** branch
