### ISSUE TITLE
Sorting members alphabetically breaks app

### ISSUE THREAD

**Issue by will-hou** [FRCTools/Attendance-Client#52]
![Capture](https://user-images.githubusercontent.com/23201789/72197493-b6233500-33d6-11ea-8731-62dfc787724e.PNG)

Strange thing is that while sorting still doesn't work, an error only shows up on the electron app preview but not on `localhost:3000` 

All of this may be due to an underlying issue with the way we've connected to the new DB because everything was working for the first couple of hours before breaking. We should probably look more into that when time allows.

The sorting has been removed in the `tempfix` branch as a temporary fix(who would've guessed) so we can still have some sort of attendance tracking. However, we probably shouldn't merge anything into `master` until we've gotten a chance to do more testing and work out any more bugs due to the DB transition.

**Comment by andrewda** [comment]
Hmmm... Does anyone have a `null` name in the database?

**Comment by will-hou** [comment]
There was an entry named `signedIn` in `users` with a nonexistent `name` field 🤦‍♂ 

I can't believe I didn't catch this earlier. I spent like an hour trying to debug the problem today and when I get home I find it in literally 2 minutes. I think I even saw it earlier and assumed it was a part of an actual user without looking closer🤦‍♂🤦‍♂🤦‍♂🤦‍♂🤦‍♂🤦‍♂🤦‍♂🤦‍♂

There's still the question of how it got there but maybe that was just a one time occurrence. Will keep watching things closely as the attendance app is used more.

Thanks for the help! Your debugging skills are truly masterful 🐞💥🔫 🙇
